-- MySQL Script generated by MySQL Workbench
-- Sun Nov 23 01:50:37 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema collab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `collab` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `collab` ;

-- -----------------------------------------------------
-- Table `collab`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collab`.`User` ;

CREATE TABLE IF NOT EXISTS `collab`.`User` (
  `UserID` INT NOT NULL,
  `Username` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Zip` INT NULL,
  `phone_number` VARCHAR(16) NULL,
  `Type` VARCHAR(45) NULL,
  `Sec1` VARCHAR(45) NULL,
  `Sec2` VARCHAR(45) NULL,
  `Sec3` VARCHAR(45) NULL,
  `Ans1` VARCHAR(45) NULL,
  `Ans2` VARCHAR(45) NULL,
  `Ans3` VARCHAR(45) NULL,
  `confirmcode` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collab`.`UserDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collab`.`UserDetails` ;

CREATE TABLE IF NOT EXISTS `collab`.`UserDetails` (
  `UserID` INT NOT NULL,
  `Education` VARCHAR(45) NOT NULL,
  `Hobbies` VARCHAR(45) NULL,
  `Profession` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  INDEX `fk_UserDetails_User1_idx` (`UserID` ASC),
  CONSTRAINT `fk_UserDetails_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `collab`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collab`.`Facilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collab`.`Facilities` ;

CREATE TABLE IF NOT EXISTS `collab`.`Facilities` (
  `FacilitiesID` INT NOT NULL,
  `RoomType` VARCHAR(45) NULL,
  `Active` TINYINT(1) NULL,
  `MaxCapacity` INT NULL,
  PRIMARY KEY (`FacilitiesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collab`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collab`.`Events` ;

CREATE TABLE IF NOT EXISTS `collab`.`Events` (
  `EventID` INT NOT NULL,
  `Month` INT NULL,
  `Day` INT NULL,
  `Year` INT NULL,
  `Time` INT NULL,
  `UserID` INT NOT NULL,
  `FacilitiesID` INT NOT NULL,
  PRIMARY KEY (`EventID`, `UserID`, `FacilitiesID`),
  INDEX `fk_Events_Facilities1_idx` (`FacilitiesID` ASC),
  INDEX `fk_Events_User1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Events_Facilities1`
    FOREIGN KEY (`FacilitiesID`)
    REFERENCES `collab`.`Facilities` (`FacilitiesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `collab`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collab`.`Invities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collab`.`Invities` ;

CREATE TABLE IF NOT EXISTS `collab`.`Invities` (
  `EventID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`EventID`, `UserID`),
  INDEX `fk_Invities_Events1_idx` (`EventID` ASC),
  INDEX `fk_Invities_User1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Invities_Events1`
    FOREIGN KEY (`EventID`)
    REFERENCES `collab`.`Events` (`EventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invities_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `collab`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
